swagger: "2.0"
info:
  title: Batcomputer API
  version: "1.0.0"
host: api.batcomputer.com
paths:
  /v1/account/collects:
    get:
      tags:
      - "collection"
      summary: "用户拥有的nft collections"
      parameters:
      - in: "query"
        name: "chain_id"
        type: integer
      - in: "query"
        name: "address"
        type: string
      - in: "query"
        name: "cat_id"
        type: integer
      responses:
        "200":
          description: "successful"
  /v1/nft/collect/rank:
    get:
      tags:
      - "collection"
      summary: "nft collection排行"
      parameters:
      - in: "query"
        name: "chain_id"
        type: integer
      - in: "query"
        name: "cat_id"
        type: integer
      - in: "query"
        name: "keyword"
        type: string
      - in: "query"
        name: "sort"
        type: integer
      responses:
        "200":
          description: "successful"
  /v1/nft/collect/rank_detail:
    get:
      tags:
      - "collection"
      summary: "nft排行里的collect详细信息"
      parameters:
      - in: "query"
        name: "chain_id"
        type: integer
      - in: "query"
        name: "contract"
        type: string
      responses:
        "200":
          description: "successful"
  /v1/category/collection:
    get:
      tags:
      - "collection"
      summary: "nft搜索排行"
      parameters:
      - in: "query"
        name: "chain_id"
        type: integer
      - in: "query"
        name: "cat_id"
        type: integer
      responses:
        "200":
          description: "successful"
