swagger: "2.0"
info:
  title: Batcomputer API
  version: "1.0.0"
host: api.batcomputer.com
paths:
  /collections:
    get:
      summary: default
      responses:
        "200":
          description: "successful"
